---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-core-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - list
      - watch
      - update
