---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.test.bdap.com
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.test.bdap.com
  resources:
  - mpijobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.test.bdap.com
  resources:
  - mpijobs/status
  verbs:
  - get
  - patch
  - update
