apiVersion: batch.test.bdap.com/v1
kind: MPIJob
metadata:
  name: simple-train
  namespace: sw-mpi-operator
spec:
  numWorkers: 3
  launcherTemplate:
    spec:
      containers:
        - args:
            - mkdir MPI-Operator &&
              cd MPI-Operator &&
              mkdir sample-python-train &&
              cd sample-python-train &&
              horovodrun -np 2 --hostfile $OMPI_MCA_orte_default_hostfile python main.py
          command:
            - /bin/sh
            - -c
          image: farawaya/horovod-torch-cpu
          name: horovod-master
      restartPolicy: Never
  workerTemplate:
    spec:
      containers:
        - args:
            - git clone https://github.com/FFFFFaraway/MPI-Operator.git &&
              cd MPI-Operator &&
              cd sample-python-train &&
              pip install -r requirements.txt &&
              touch /ready.txt &&
              sleep infinity
          command:
            - /bin/sh
            - -c
          image: farawaya/horovod-torch-cuda113
          name: horovod-worker
          resources:
            limits:
              nvidia.com/gpu: 1
          readinessProbe:
            exec:
              command:
                - cat
                - /ready.txt
            initialDelaySeconds: 30
            periodSeconds: 5
      tolerations:
        - effect: NoSchedule
          key: gpu
          operator: Exists
      restartPolicy: OnFailure
