apiVersion: batch.test.bdap.com/v1
kind: MPIJob
metadata:
  name: simple-train
  namespace: sw-mpi-operator
spec:
  numWorkers: 3
  launcherTemplate:
    spec:
      containers:
        - args:
            - sleep 30s && mkdir MPI-Operator && cd MPI-Operator &&
              mkdir sample-python-train && cd sample-python-train &&
              horovodrun -np 2 --hostfile $OMPI_MCA_orte_default_hostfile python main.py
          command:
            - /bin/sh
            - -c
          image: coreharbor.bdap.com/library/horovod-sw-base
          name: horovod-master
      restartPolicy: Never
  workerTemplate:
    spec:
      containers:
        - args:
            - git clone https://github.com/FFFFFaraway/MPI-Operator.git
              && cd sample-python-train && pip install -r requirements.txt && sleep infinity
          command:
            - /bin/sh
            - -c
          image: coreharbor.bdap.com/library/horovod-sw-base
          name: horovod-worker
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
        - effect: NoSchedule
          key: gpu
          operator: Exists
      restartPolicy: OnFailure
